"""track registry document status

Revision ID: 50a1aafe5939
Revises: f0f8b21570b6
Create Date: 2026-08-25 21:15:19.368404

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "50a1aafe5939"
down_revision = "f0f8b21570b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("olympiad_editions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "registry_status",
                sa.Enum(
                    "not_listed",
                    "draft",
                    "approved",
                    "previous_year",
                    name="registrystatus",
                    native_enum=False,
                    length=40,
                ),
                server_default=sa.text("'not_listed'"),
                nullable=False,
            )
        )
        batch_op.create_index(
            batch_op.f("ix_olympiad_editions_registry_status"),
            ["registry_status"],
            unique=False,
        )
        batch_op.alter_column("registry_status", server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("olympiad_editions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_olympiad_editions_registry_status"))
        batch_op.drop_column("registry_status")

    # ### end Alembic commands ###
