"""initial catalog schema

Revision ID: f0f8b21570b6
Revises:
Create Date: 2026-08-25 21:08:15.881419

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f0f8b21570b6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admins")),
    )
    with op.batch_alter_table("admins", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_admins_username"), ["username"], unique=True)

    op.create_table(
        "olympiads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("family_name", sa.String(length=255), nullable=False),
        sa.Column("profile", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("organizer", sa.String(length=255), nullable=True),
        sa.Column("website_url", sa.String(length=1000), nullable=False),
        sa.Column("logo_url", sa.String(length=1000), nullable=True),
        sa.Column(
            "geography",
            sa.Enum(
                "russia", "moscow", "russia_moscow", name="geography", native_enum=False, length=40
            ),
            nullable=False,
        ),
        sa.Column("is_team", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_olympiads")),
    )
    with op.batch_alter_table("olympiads", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_olympiads_family_name"), ["family_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_olympiads_is_team"), ["is_team"], unique=False)
        batch_op.create_index(batch_op.f("ix_olympiads_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_olympiads_profile"), ["profile"], unique=False)
        batch_op.create_index(batch_op.f("ix_olympiads_slug"), ["slug"], unique=True)

    op.create_table(
        "universities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("short_name", sa.String(length=100), nullable=True),
        sa.Column("website_url", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_universities")),
        sa.UniqueConstraint("name", name=op.f("uq_universities_name")),
    )
    with op.batch_alter_table("universities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_universities_slug"), ["slug"], unique=True)

    op.create_table(
        "materials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("olympiad_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "material_type",
            sa.Enum(
                "tasks",
                "solutions",
                "video",
                "course",
                "archive",
                "other",
                name="materialtype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("year", sa.SmallInteger(), nullable=True),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("is_official", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["olympiad_id"],
            ["olympiads.id"],
            name=op.f("fk_materials_olympiad_id_olympiads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_materials")),
    )
    with op.batch_alter_table("materials", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_materials_olympiad_id"), ["olympiad_id"], unique=False)

    op.create_table(
        "olympiad_editions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("olympiad_id", sa.Integer(), nullable=False),
        sa.Column("academic_year", sa.String(length=9), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft", "published", "archived", name="editionstatus", native_enum=False, length=40
            ),
            nullable=False,
        ),
        sa.Column(
            "data_status",
            sa.Enum(
                "confirmed",
                "partial",
                "previous_year_estimate",
                "announcement_pending",
                name="datastatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("is_in_registry", sa.Boolean(), nullable=False),
        sa.Column("registry_level", sa.SmallInteger(), nullable=True),
        sa.Column("is_popular", sa.Boolean(), nullable=False),
        sa.Column("registration_url", sa.String(length=1000), nullable=True),
        sa.Column("previous_year_reference", sa.String(length=9), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "registry_level IS NULL OR registry_level BETWEEN 1 AND 3",
            name=op.f("ck_olympiad_editions_valid_registry_level"),
        ),
        sa.ForeignKeyConstraint(
            ["olympiad_id"],
            ["olympiads.id"],
            name=op.f("fk_olympiad_editions_olympiad_id_olympiads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_olympiad_editions")),
        sa.UniqueConstraint("olympiad_id", "academic_year", name="edition_olympiad_year"),
    )
    with op.batch_alter_table("olympiad_editions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_olympiad_editions_academic_year"), ["academic_year"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_olympiad_editions_is_in_registry"), ["is_in_registry"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_olympiad_editions_is_popular"), ["is_popular"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_olympiad_editions_registry_level"), ["registry_level"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_olympiad_editions_status"), ["status"], unique=False)

    op.create_table(
        "benefits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("edition_id", sa.Integer(), nullable=False),
        sa.Column("university_id", sa.Integer(), nullable=True),
        sa.Column(
            "benefit_type",
            sa.Enum(
                "bvi",
                "hundred_points",
                "grant",
                "prize",
                "other",
                name="benefittype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("diploma_requirement", sa.String(length=255), nullable=True),
        sa.Column("ege_subject", sa.String(length=160), nullable=True),
        sa.Column("ege_min_score", sa.SmallInteger(), nullable=True),
        sa.Column("admission_year", sa.SmallInteger(), nullable=True),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["edition_id"],
            ["olympiad_editions.id"],
            name=op.f("fk_benefits_edition_id_olympiad_editions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["university_id"],
            ["universities.id"],
            name=op.f("fk_benefits_university_id_universities"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_benefits")),
    )
    with op.batch_alter_table("benefits", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_benefits_edition_id"), ["edition_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_benefits_university_id"), ["university_id"], unique=False
        )

    op.create_table(
        "edition_grades",
        sa.Column("edition_id", sa.Integer(), nullable=False),
        sa.Column("grade", sa.SmallInteger(), nullable=False),
        sa.CheckConstraint("grade BETWEEN 5 AND 11", name=op.f("ck_edition_grades_valid_grade")),
        sa.ForeignKeyConstraint(
            ["edition_id"],
            ["olympiad_editions.id"],
            name=op.f("fk_edition_grades_edition_id_olympiad_editions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("edition_id", "grade", name=op.f("pk_edition_grades")),
    )
    op.create_table(
        "source_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("edition_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("publisher", sa.String(length=255), nullable=True),
        sa.Column("source_type", sa.String(length=80), nullable=True),
        sa.Column("source_year", sa.String(length=9), nullable=True),
        sa.Column("accessed_on", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["edition_id"],
            ["olympiad_editions.id"],
            name=op.f("fk_source_links_edition_id_olympiad_editions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_links")),
    )
    with op.batch_alter_table("source_links", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_source_links_edition_id"), ["edition_id"], unique=False
        )

    op.create_table(
        "stages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("edition_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("stage_type", sa.String(length=80), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=True),
        sa.Column("ends_on", sa.Date(), nullable=True),
        sa.Column("registration_opens_on", sa.Date(), nullable=True),
        sa.Column("registration_closes_on", sa.Date(), nullable=True),
        sa.Column(
            "date_precision",
            sa.Enum(
                "exact",
                "range",
                "month",
                "approximate",
                "tba",
                name="dateprecision",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("is_date_confirmed", sa.Boolean(), nullable=False),
        sa.Column(
            "format",
            sa.Enum(
                "online",
                "offline",
                "hybrid",
                "unknown",
                name="eventformat",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("location", sa.String(length=500), nullable=True),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("position >= 0", name=op.f("ck_stages_nonnegative_position")),
        sa.ForeignKeyConstraint(
            ["edition_id"],
            ["olympiad_editions.id"],
            name=op.f("fk_stages_edition_id_olympiad_editions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stages")),
    )
    with op.batch_alter_table("stages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_stages_edition_id"), ["edition_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stages_edition_id"))

    op.drop_table("stages")
    with op.batch_alter_table("source_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_links_edition_id"))

    op.drop_table("source_links")
    op.drop_table("edition_grades")
    with op.batch_alter_table("benefits", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_benefits_university_id"))
        batch_op.drop_index(batch_op.f("ix_benefits_edition_id"))

    op.drop_table("benefits")
    with op.batch_alter_table("olympiad_editions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_olympiad_editions_status"))
        batch_op.drop_index(batch_op.f("ix_olympiad_editions_registry_level"))
        batch_op.drop_index(batch_op.f("ix_olympiad_editions_is_popular"))
        batch_op.drop_index(batch_op.f("ix_olympiad_editions_is_in_registry"))
        batch_op.drop_index(batch_op.f("ix_olympiad_editions_academic_year"))

    op.drop_table("olympiad_editions")
    with op.batch_alter_table("materials", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_materials_olympiad_id"))

    op.drop_table("materials")
    with op.batch_alter_table("universities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_universities_slug"))

    op.drop_table("universities")
    with op.batch_alter_table("olympiads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_olympiads_slug"))
        batch_op.drop_index(batch_op.f("ix_olympiads_profile"))
        batch_op.drop_index(batch_op.f("ix_olympiads_name"))
        batch_op.drop_index(batch_op.f("ix_olympiads_is_team"))
        batch_op.drop_index(batch_op.f("ix_olympiads_family_name"))

    op.drop_table("olympiads")
    with op.batch_alter_table("admins", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_admins_username"))

    op.drop_table("admins")
    # ### end Alembic commands ###
